/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carts: typeof import('./src/components/Carts.vue')['default']
    Dots: typeof import('./src/components/Dots.vue')['default']
    IconBluePlusInCircle: typeof import('./src/assets/icons/IconBluePlusInCircle.vue')['default']
    IconCrossedCart: typeof import('./src/assets/icons/IconCrossedCart.vue')['default']
    IconDelete: typeof import('./src/assets/icons/IconDelete.vue')['default']
    IconEmptyCart: typeof import('./src/assets/icons/IconEmptyCart.vue')['default']
    IconFullCart: typeof import('./src/assets/icons/IconFullCart.vue')['default']
    IconMinus: typeof import('./src/assets/icons/IconMinus.vue')['default']
    IconNoNetworkConn: typeof import('./src/assets/icons/IconNoNetworkConn.vue')['default']
    IconPlus: typeof import('./src/assets/icons/IconPlus.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    Quantity: typeof import('./src/components/Quantity.vue')['default']
    QuantityInput: typeof import('./src/components/QuantityInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    Todos: typeof import('./src/components/Todos.vue')['default']
  }
}
